# Mod properties
mod.id = cmmce
mod.name = CMM Collision Expand
mod.version = 0.1.0
mod.description = Increase collision box size to match the CMMRP models.
mod.group = com.rassvet_ii.cmmce

# Used for the mod metadata
mod.mc_dep_fabric = [VERSIONED]
mod.mc_dep_forgelike = [VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title = [VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets = [VERSIONED]

# Mod setup
deps.mixin_extras=0.4.1
deps.fabric_loader=0.16.10
deps.fabric_version=[VERSIONED]

deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.parchment=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.architectury_api=[VERSIONED]
deps.yacl = 3.6.6

# Publishing
publish.modrinth=
publish.curseforge=

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
