modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cmmce"
version = "${version}"
displayName = "CMM Collision Expand"
authors = "rassvet_ii"
description = '''
Increase collision box size to match the CMMRP models.
'''
#logoFile = ""

[[dependencies.cmmce]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cmmce]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cmmce]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cmmce]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[3.6.6,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "cmmce.mixins.json"
