modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "rassvet_ii"
description = '''
${mod_description}
'''
logoFile = "assets/cmmce/icon.png"

[["dependencies.${cmmce}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[["dependencies.${cmmce}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[["dependencies.${cmmce}"]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[["dependencies.${cmmce}"]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[${yacL_version_id},)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "cmmce.mixins.json"
