mod.mc_dep_fabric==1.20.1
mod.mc_dep_forgelike=[1.20, 1.20.1]
mod.mc_title=1.20.1
mod.mc_targets=1.20.1

deps.forge_loader=47.4.1
deps.neoforge_loader=[UNSUPPORTED]

deps.parchment=2023.09.03
deps.fabric_version=0.92.6+1.20.1

deps.modmenu_version=7.2.2
deps.architectury_api=9.2.14

loom.platform=forge
